# Generated by Django 2.0.7 on 2018-11-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('keyword', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-date', 'stock'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(default=0)),
                ('min_price', models.IntegerField(default=0)),
                ('sales_amount', models.IntegerField(default=0)),
                ('updown', models.IntegerField(default=None)),
                ('updown_percentage', models.FloatField(default=None)),
            ],
            options={
                'ordering': ['stock', '-date', '-updown_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Stocklist',
            fields=[
                ('stock_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.Stocklist'),
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.Stocklist'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('stock', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('stock', 'title', 'date')},
        ),
    ]
