# Generated by Django 2.0.7 on 2018-10-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board2', '0002_auto_20181025_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
