# Generated by Django 2.0.7 on 2018-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board2', '0003_remove_post_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
