# Generated by Django 2.0.7 on 2018-10-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board2', '0005_auto_20181025_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload',
        ),
    ]
