# Generated by Django 2.0.7 on 2018-10-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20181026_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='board2.Comment'),
        ),
    ]
